#!/bin/bash
# Set up host infrastructure for hardware board testing (Phase 6a).
# DHCP: systemd-networkd built-in DHCPServer (no extra package, runs as root).
# TFTP: atftpd (atftp package, runs as root, no Landlock/sandbox issues).
# Also: systemd-networkd static-IP config, USB relay udev rule, TFTP_DIR.
# Idempotent — safe to run multiple times.
# DRY_RUN=1: print what would be done without writing any files or installing packages.
# Usage: lib/hw-bootstrap.sh <tftp_dir> <hw_iface> <hw_host_ip> <hw_dhcp_range> <relay_vid> <relay_pid>
set -euo pipefail
. "$(dirname "$0")/common.sh"

TFTP_DIR="${1:?usage: hw-bootstrap.sh <tftp_dir> <hw_iface> <hw_host_ip> <hw_dhcp_range> <relay_vid> <relay_pid>}"
HW_IFACE="${2:?}"
HW_HOST_IP="${3:?}"
HW_DHCP_RANGE="${4:?}"
HW_RELAY_VID="${5:?}"
HW_RELAY_PID="${6:?}"

[[ "$HW_RELAY_VID" =~ ^[0-9a-f]{4}$ ]] \
    || die "HW_RELAY_VID='$HW_RELAY_VID' must be 4 lowercase hex digits (e.g. 1a86)"
[[ "$HW_RELAY_PID" =~ ^[0-9a-f]{4}$ ]] \
    || die "HW_RELAY_PID='$HW_RELAY_PID' must be 4 lowercase hex digits (e.g. 7523)"

DRY_RUN=${DRY_RUN:-0}

# ── Root vs sudo ───────────────────────────────────────────────────────────────
if [[ $EUID -eq 0 ]]; then SUDO=""; else SUDO="sudo"; fi

# ── Serial group: Debian/Ubuntu/Fedora use "dialout"; Arch uses "uucp" ────────
SERIAL_GROUP=$(getent group dialout &>/dev/null && echo dialout || echo uucp)

# ── Helpers ────────────────────────────────────────────────────────────────────

dry_info() { printf '[hw-bootstrap] (dry-run) %s\n' "$*"; }

write_file() {
    local path="$1"; shift
    local content="$*"
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would write: $path"
        printf '%s\n' "$content"
        return
    fi
    # Skip write when content is identical — avoids triggering unnecessary service restarts.
    if [[ -f "$path" ]] && diff <(printf '%s\n' "$content") "$path" &>/dev/null; then
        info "unchanged: $path"
        return
    fi
    $SUDO mkdir -p "$(dirname "$path")"
    printf '%s\n' "$content" | $SUDO tee "$path" > /dev/null
    info "wrote: $path"
}

run_cmd() {
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would run: $*"
        return
    fi
    "$@"
}

# ── Package install ────────────────────────────────────────────────────────────

detect_pm() {
    if   command -v pacman  &>/dev/null; then echo pacman
    elif command -v apt-get &>/dev/null; then echo apt
    elif command -v dnf     &>/dev/null; then echo dnf
    else echo unknown
    fi
}

install_atftpd() {
    local pm
    pm=$(detect_pm)
    if command -v atftpd &>/dev/null; then
        info "atftpd already installed"
        return
    fi
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would install: atftp (pm: $pm)"
        return
    fi
    case "$pm" in
        pacman) $SUDO pacman -S --needed --noconfirm atftp ;;
        apt)    $SUDO apt-get install -y atftpd ;;
        dnf)    $SUDO dnf install -y atftp ;;
        *)      die "No supported package manager found — install atftp manually" ;;
    esac
}

# ── atftpd service ─────────────────────────────────────────────────────────────
# Runs as root: can bind port 69 (TFTP) and read TFTP_DIR from anywhere,
# including /home/…  No Landlock sandbox, no privilege-drop complications.
# Type=simple + --no-fork keeps atftpd in the foreground for journald.

kt_atftpd_service() {
    cat <<EOF
# kernel-test hardware test network — generated by make hw-bootstrap
[Unit]
Description=kernel-test TFTP server for ${HW_IFACE}
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/atftpd --no-fork ${TFTP_DIR}
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
}

# ── systemd-networkd config ────────────────────────────────────────────────────
# [Network]: static IP + ConfigureWithoutCarrier + enables built-in DHCP server.
# [DHCPServer]: pool derived from HW_DHCP_RANGE (last octet, /24 assumed).
#   BootServerAddress → DHCP option 66 (next-server / TFTP server IP).
#   BootFilename      → DHCP option 67 (boot file name sent to U-Boot).
# U-Boot dhcp command reads both options, sets serverip + bootfile automatically.

networkd_conf() {
    local dhcp_start dhcp_end pool_offset pool_size
    dhcp_start="${HW_DHCP_RANGE%%,*}"
    dhcp_end="${HW_DHCP_RANGE##*,}"
    pool_offset="${dhcp_start##*.}"
    pool_size=$(( ${dhcp_end##*.} - ${dhcp_start##*.} + 1 ))
    cat <<EOF
# kernel-test hardware test network — generated by make hw-bootstrap
[Match]
Name=${HW_IFACE}

[Network]
ConfigureWithoutCarrier=yes
Address=${HW_HOST_IP}/24
DHCPServer=yes

[DHCPServer]
PoolOffset=${pool_offset}
PoolSize=${pool_size}
EmitDNS=no
EmitNTP=no
BootServerAddress=${HW_HOST_IP}
BootFilename=Image
EOF
}

# ── NetworkManager: mark HW_IFACE unmanaged ───────────────────────────────────
# When NetworkManager runs alongside systemd-networkd, NM reconfigures HW_IFACE
# on every carrier event (cable unplug/replug), stripping the static IP networkd
# assigned. Writing an unmanaged-devices entry makes NM ignore HW_IFACE entirely.

nm_unmanaged_conf() {
    cat <<EOF
# kernel-test hardware test network — generated by make hw-bootstrap
# Prevents NetworkManager from removing the static IP on HW_IFACE.
[keyfile]
unmanaged-devices=interface-name:${HW_IFACE}
EOF
}

# ── udev rule ──────────────────────────────────────────────────────────────────
# Creates stable /dev/vf2-relay symlink; sets group=dialout mode=0664.
# CH340 default VID=1a86 PID=7523; override with HW_RELAY_VID/HW_RELAY_PID in local.mk.
# Find your relay's IDs: udevadm info /dev/ttyUSB0 | grep ID_VENDOR_ID\|ID_MODEL_ID

udev_rule() {
    cat <<EOF
# VF2 USB relay board_reset — generated by make hw-bootstrap
# VID=${HW_RELAY_VID} PID=${HW_RELAY_PID} (CH340 default; override: HW_RELAY_VID/HW_RELAY_PID in local.mk)
# CH340-based relays enumerate as tty (SUBSYSTEM=="tty", /dev/ttyUSBx).
# HID-based relays (Ucreatefun etc.) enumerate as hidraw: change SUBSYSTEM=="tty" to SUBSYSTEM=="hidraw".
# Find your relay's IDs: udevadm info /dev/ttyUSB0 | grep ID_VENDOR_ID\|ID_MODEL_ID
SUBSYSTEM=="tty", ATTRS{idVendor}=="${HW_RELAY_VID}", ATTRS{idProduct}=="${HW_RELAY_PID}", GROUP="${SERIAL_GROUP}", MODE="0664", SYMLINK+="vf2-relay"
EOF
}

# ── Main ───────────────────────────────────────────────────────────────────────

if [[ $DRY_RUN -eq 1 ]]; then
    info "=== hw-bootstrap: hardware test network setup (DRY RUN) ==="
else
    info "=== hw-bootstrap: hardware test network setup ==="
fi
info "  HW_IFACE      = $HW_IFACE"
info "  HW_HOST_IP    = $HW_HOST_IP"
info "  HW_DHCP_RANGE = $HW_DHCP_RANGE"
info "  TFTP_DIR      = $TFTP_DIR"
info "  Relay VID:PID = ${HW_RELAY_VID}:${HW_RELAY_PID}"

# 1. Install atftpd
info "--- [1/6] atftpd package"
install_atftpd

# 2. atftpd service
info "--- [2/6] atftpd service → /etc/systemd/system/kernel-test-atftpd.service"
write_file /etc/systemd/system/kernel-test-atftpd.service "$(kt_atftpd_service)"

# 3. systemd-networkd config (static IP + built-in DHCP server)
info "--- [3/6] systemd-networkd (DHCP server) → /etc/systemd/network/50-vf2.network"
write_file /etc/systemd/network/50-vf2.network "$(networkd_conf)"

# 4. NetworkManager unmanaged rule (only when NM is running)
info "--- [4/6] NetworkManager unmanaged rule"
if systemctl is-active --quiet NetworkManager 2>/dev/null; then
    write_file /etc/NetworkManager/conf.d/99-vf2-unmanaged.conf "$(nm_unmanaged_conf)"
else
    info "NetworkManager not active — skipping"
fi

# 5. udev rule
info "--- [5/6] udev rule → /etc/udev/rules.d/99-vf2-relay.rules"
write_file /etc/udev/rules.d/99-vf2-relay.rules "$(udev_rule)"

# 6. TFTP dir
info "--- [6/6] TFTP directory: $TFTP_DIR"
if [[ $DRY_RUN -eq 1 ]]; then
    dry_info "would create: $TFTP_DIR"
else
    if [[ ! -d "$TFTP_DIR" ]]; then
        mkdir -p "$TFTP_DIR"
        info "created: $TFTP_DIR"
    else
        info "exists: $TFTP_DIR"
    fi
fi

# ── Activate (skip in dry-run) ─────────────────────────────────────────────────

if [[ $DRY_RUN -eq 0 ]]; then
    info "--- activating services"
    run_cmd $SUDO udevadm control --reload-rules
    run_cmd $SUDO udevadm trigger --subsystem-match=tty --subsystem-match=hidraw
    if systemctl is-active --quiet NetworkManager 2>/dev/null; then
        run_cmd $SUDO nmcli general reload
    fi
    run_cmd $SUDO systemctl enable --now systemd-networkd
    run_cmd $SUDO systemctl restart systemd-networkd
    run_cmd $SUDO networkctl reconfigure "$HW_IFACE"
    run_cmd $SUDO systemctl daemon-reload
    run_cmd $SUDO systemctl enable --now kernel-test-atftpd
fi

if [[ $DRY_RUN -eq 1 ]]; then
    info "=== hw-bootstrap complete (DRY RUN) ==="
else
    info "=== hw-bootstrap complete ==="
fi

if [[ $DRY_RUN -eq 0 ]]; then
    printf '\nNext steps:\n'
    printf '  1. Plug in the USB relay — verify: ls -la /dev/vf2-relay\n'
    printf '  2. Connect Ethernet cable: laptop %s ↔ switch ↔ VF2 board\n' "$HW_IFACE"
    printf '  3. Run: make hw-deploy  (copies kernel + initramfs to %s/)\n' "$TFTP_DIR"
    printf '  4. Set U-Boot bootcmd once (see docs/hw-bootstrap-plan.md)\n'
    printf '  5. Run: make hw BOARD_TTY=/dev/ttyUSB0\n'
    printf '  Verify DHCP: journalctl -u systemd-networkd -f\n'
    printf '  Verify TFTP: journalctl -u kernel-test-atftpd -f\n'
fi
