#!/bin/bash
# Set up host infrastructure for hardware board testing (Phase 6a).
# Installs dnsmasq (DHCP+TFTP on HW_IFACE), systemd-networkd static-IP config,
# USB relay udev rule, and creates TFTP_DIR.
# Idempotent — safe to run multiple times.
# DRY_RUN=1: print what would be done without writing any files or installing packages.
# Usage: lib/hw-bootstrap.sh <tftp_dir> <hw_iface> <hw_host_ip> <hw_dhcp_range> <relay_vid> <relay_pid>
set -euo pipefail
. "$(dirname "$0")/common.sh"

TFTP_DIR="${1:?usage: hw-bootstrap.sh <tftp_dir> <hw_iface> <hw_host_ip> <hw_dhcp_range> <relay_vid> <relay_pid>}"
HW_IFACE="${2:?}"
HW_HOST_IP="${3:?}"
HW_DHCP_RANGE="${4:?}"
HW_RELAY_VID="${5:?}"
HW_RELAY_PID="${6:?}"

[[ "$HW_RELAY_VID" =~ ^[0-9a-f]{4}$ ]] \
    || die "HW_RELAY_VID='$HW_RELAY_VID' must be 4 lowercase hex digits (e.g. 1a86)"
[[ "$HW_RELAY_PID" =~ ^[0-9a-f]{4}$ ]] \
    || die "HW_RELAY_PID='$HW_RELAY_PID' must be 4 lowercase hex digits (e.g. 7523)"

DRY_RUN=${DRY_RUN:-0}

# ── Root vs sudo ───────────────────────────────────────────────────────────────
if [[ $EUID -eq 0 ]]; then SUDO=""; else SUDO="sudo"; fi

# ── Helpers ────────────────────────────────────────────────────────────────────

dry_info() { printf '[hw-bootstrap] (dry-run) %s\n' "$*"; }

write_file() {
    local path="$1"; shift
    local content="$*"
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would write: $path"
        printf '%s\n' "$content"
        return
    fi
    # Skip write when content is identical — avoids triggering unnecessary service restarts.
    if [[ -f "$path" ]] && diff <(printf '%s\n' "$content") "$path" &>/dev/null; then
        info "unchanged: $path"
        return
    fi
    $SUDO mkdir -p "$(dirname "$path")"
    printf '%s\n' "$content" | $SUDO tee "$path" > /dev/null
    info "wrote: $path"
}

run_cmd() {
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would run: $*"
        return
    fi
    "$@"
}

# ── Package install ────────────────────────────────────────────────────────────

detect_pm() {
    if   command -v pacman  &>/dev/null; then echo pacman
    elif command -v apt-get &>/dev/null; then echo apt
    elif command -v dnf     &>/dev/null; then echo dnf
    else echo unknown
    fi
}

install_dnsmasq() {
    local pm
    pm=$(detect_pm)
    if command -v dnsmasq &>/dev/null; then
        info "dnsmasq already installed"
        return
    fi
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would install: dnsmasq (pm: $pm)"
        return
    fi
    case "$pm" in
        pacman) $SUDO pacman -S --needed --noconfirm dnsmasq ;;
        apt)    $SUDO apt-get install -y dnsmasq ;;
        dnf)    $SUDO dnf install -y dnsmasq ;;
        *)      die "No supported package manager found — install dnsmasq manually" ;;
    esac
}

# ── dnsmasq config ─────────────────────────────────────────────────────────────
# bind-interfaces: dnsmasq only listens on HW_IFACE, never touches main LAN DHCP.
# dhcp-boot: injects next-server (serverip) into DHCP reply → U-Boot dhcp sets
#            serverip automatically, no manual setenv needed.

dnsmasq_conf() {
    cat <<EOF
# kernel-test hardware test network — generated by make hw-bootstrap
# Edit HW_IFACE / HW_HOST_IP / HW_DHCP_RANGE in local.mk to customise.
interface=${HW_IFACE}
bind-interfaces
dhcp-range=${HW_DHCP_RANGE},1h
dhcp-option=option:router
enable-tftp
tftp-root=${TFTP_DIR}
dhcp-boot=Image,,${HW_HOST_IP}
EOF
}

# ── systemd-networkd config ────────────────────────────────────────────────────
# Assigns HW_HOST_IP/24 to HW_IFACE as a static address.
# Only active on machines running systemd-networkd (not Hetzner).

networkd_conf() {
    cat <<EOF
# kernel-test hardware test network — generated by make hw-bootstrap
[Match]
Name=${HW_IFACE}

[Network]
Address=${HW_HOST_IP}/24
EOF
}

# ── udev rule ──────────────────────────────────────────────────────────────────
# Creates stable /dev/vf2-relay symlink; sets group=dialout mode=0664.
# CH340 default VID=1a86 PID=7523; override with HW_RELAY_VID/HW_RELAY_PID in local.mk.
# Find your relay's IDs: udevadm info /dev/ttyUSB0 | grep ID_VENDOR_ID\|ID_MODEL_ID

udev_rule() {
    cat <<EOF
# VF2 USB relay board_reset — generated by make hw-bootstrap
# VID=${HW_RELAY_VID} PID=${HW_RELAY_PID} (CH340 default; override: HW_RELAY_VID/HW_RELAY_PID in local.mk)
# CH340-based relays enumerate as tty (SUBSYSTEM=="tty", /dev/ttyUSBx).
# HID-based relays (Ucreatefun etc.) enumerate as hidraw: change SUBSYSTEM=="tty" to SUBSYSTEM=="hidraw".
# Find your relay's IDs: udevadm info /dev/ttyUSB0 | grep ID_VENDOR_ID\|ID_MODEL_ID
SUBSYSTEM=="tty", ATTRS{idVendor}=="${HW_RELAY_VID}", ATTRS{idProduct}=="${HW_RELAY_PID}", GROUP="dialout", MODE="0664", SYMLINK+="vf2-relay"
EOF
}

# ── Main ───────────────────────────────────────────────────────────────────────

info "=== hw-bootstrap: hardware test network setup${DRY_RUN:+ (DRY RUN)} ==="
info "  HW_IFACE      = $HW_IFACE"
info "  HW_HOST_IP    = $HW_HOST_IP"
info "  HW_DHCP_RANGE = $HW_DHCP_RANGE"
info "  TFTP_DIR      = $TFTP_DIR"
info "  Relay VID:PID = ${HW_RELAY_VID}:${HW_RELAY_PID}"

# 1. Install dnsmasq
info "--- [1/5] dnsmasq package"
install_dnsmasq

# 2. dnsmasq config
info "--- [2/5] dnsmasq config → /etc/dnsmasq.d/vf2.conf"
write_file /etc/dnsmasq.d/vf2.conf "$(dnsmasq_conf)"

# 3. systemd-networkd config
info "--- [3/5] systemd-networkd → /etc/systemd/network/50-vf2.network"
write_file /etc/systemd/network/50-vf2.network "$(networkd_conf)"

# 4. udev rule
info "--- [4/5] udev rule → /etc/udev/rules.d/99-vf2-relay.rules"
write_file /etc/udev/rules.d/99-vf2-relay.rules "$(udev_rule)"

# 5. TFTP dir
info "--- [5/5] TFTP directory: $TFTP_DIR"
if [[ $DRY_RUN -eq 1 ]]; then
    dry_info "would create: $TFTP_DIR"
else
    mkdir -p "$TFTP_DIR"
    info "created: $TFTP_DIR"
fi

# ── Activate (skip in dry-run) ─────────────────────────────────────────────────

if [[ $DRY_RUN -eq 0 ]]; then
    info "--- activating services"
    run_cmd $SUDO udevadm control --reload-rules
    run_cmd $SUDO udevadm trigger --subsystem-match=tty --subsystem-match=hidraw
    run_cmd $SUDO systemctl enable --now systemd-networkd
    run_cmd $SUDO systemctl restart dnsmasq
fi

info "=== hw-bootstrap complete${DRY_RUN:+ (DRY RUN)} ==="

if [[ $DRY_RUN -eq 0 ]]; then
    printf '\nNext steps:\n'
    printf '  1. Plug in the USB relay — verify: ls -la /dev/vf2-relay\n'
    printf '  2. Connect Ethernet cable: laptop %s ↔ switch ↔ VF2 board\n' "$HW_IFACE"
    printf '  3. Run: make hw-deploy  (copies kernel + initramfs to %s/)\n' "$TFTP_DIR"
    printf '  4. Set U-Boot bootcmd once (see docs/hw-bootstrap-plan.md)\n'
    printf '  5. Run: make hw BOARD_TTY=/dev/ttyUSB0\n'
fi
