#!/bin/bash
# Set up host infrastructure for hardware board testing (Phase 6a).
# Installs dnsmasq (DHCP+TFTP on HW_IFACE), systemd-networkd static-IP config,
# USB relay udev rule, and creates TFTP_DIR.
# Idempotent — safe to run multiple times.
# DRY_RUN=1: print what would be done without writing any files or installing packages.
# Usage: lib/hw-bootstrap.sh <tftp_dir> <hw_iface> <hw_host_ip> <hw_dhcp_range> <relay_vid> <relay_pid>
set -euo pipefail
. "$(dirname "$0")/common.sh"

TFTP_DIR="${1:?usage: hw-bootstrap.sh <tftp_dir> <hw_iface> <hw_host_ip> <hw_dhcp_range> <relay_vid> <relay_pid>}"
HW_IFACE="${2:?}"
HW_HOST_IP="${3:?}"
HW_DHCP_RANGE="${4:?}"
HW_RELAY_VID="${5:?}"
HW_RELAY_PID="${6:?}"

[[ "$HW_RELAY_VID" =~ ^[0-9a-f]{4}$ ]] \
    || die "HW_RELAY_VID='$HW_RELAY_VID' must be 4 lowercase hex digits (e.g. 1a86)"
[[ "$HW_RELAY_PID" =~ ^[0-9a-f]{4}$ ]] \
    || die "HW_RELAY_PID='$HW_RELAY_PID' must be 4 lowercase hex digits (e.g. 7523)"

DRY_RUN=${DRY_RUN:-0}

# ── Root vs sudo ───────────────────────────────────────────────────────────────
if [[ $EUID -eq 0 ]]; then SUDO=""; else SUDO="sudo"; fi

# ── Serial group: Debian/Ubuntu/Fedora use "dialout"; Arch uses "uucp" ────────
SERIAL_GROUP=$(getent group dialout &>/dev/null && echo dialout || echo uucp)

# ── Helpers ────────────────────────────────────────────────────────────────────

dry_info() { printf '[hw-bootstrap] (dry-run) %s\n' "$*"; }

write_file() {
    local path="$1"; shift
    local content="$*"
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would write: $path"
        printf '%s\n' "$content"
        return
    fi
    # Skip write when content is identical — avoids triggering unnecessary service restarts.
    if [[ -f "$path" ]] && diff <(printf '%s\n' "$content") "$path" &>/dev/null; then
        info "unchanged: $path"
        return
    fi
    $SUDO mkdir -p "$(dirname "$path")"
    printf '%s\n' "$content" | $SUDO tee "$path" > /dev/null
    info "wrote: $path"
}

run_cmd() {
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would run: $*"
        return
    fi
    "$@"
}

# ── Package install ────────────────────────────────────────────────────────────

detect_pm() {
    if   command -v pacman  &>/dev/null; then echo pacman
    elif command -v apt-get &>/dev/null; then echo apt
    elif command -v dnf     &>/dev/null; then echo dnf
    else echo unknown
    fi
}

install_dnsmasq() {
    local pm
    pm=$(detect_pm)
    if command -v dnsmasq &>/dev/null; then
        info "dnsmasq already installed"
        return
    fi
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would install: dnsmasq (pm: $pm)"
        return
    fi
    case "$pm" in
        pacman) $SUDO pacman -S --needed --noconfirm dnsmasq ;;
        apt)    $SUDO apt-get install -y dnsmasq ;;
        dnf)    $SUDO dnf install -y dnsmasq ;;
        *)      die "No supported package manager found — install dnsmasq manually" ;;
    esac
}

# ── dnsmasq conf.d inclusion ──────────────────────────────────────────────────
# Debian/Ubuntu enable conf-dir=/etc/dnsmasq.d/,*.conf by default; Arch does not.
# Append the directive when absent so vf2.conf is actually loaded.

ensure_dnsmasq_confd() {
    local conf="/etc/dnsmasq.conf"
    [[ -f "$conf" ]] || return 0
    if grep -q '^conf-dir=.*/etc/dnsmasq.d' "$conf" 2>/dev/null; then
        info "dnsmasq: conf-dir already enabled"
        return
    fi
    if [[ $DRY_RUN -eq 1 ]]; then
        dry_info "would append: conf-dir=/etc/dnsmasq.d/,*.conf to $conf"
        return
    fi
    printf '\n# kernel-test: load per-service configs\nconf-dir=/etc/dnsmasq.d/,*.conf\n' \
        | $SUDO tee -a "$conf" > /dev/null
    info "enabled: conf-dir=/etc/dnsmasq.d/,*.conf in $conf"
}

# ── dnsmasq config ─────────────────────────────────────────────────────────────
# bind-interfaces: dnsmasq only listens on HW_IFACE, never touches main LAN DHCP.
# dhcp-boot: injects next-server (serverip) into DHCP reply → U-Boot dhcp sets
#            serverip automatically, no manual setenv needed.

dnsmasq_conf() {
    cat <<EOF
# kernel-test hardware test network — generated by make hw-bootstrap
# Edit HW_IFACE / HW_HOST_IP / HW_DHCP_RANGE in local.mk to customise.
interface=${HW_IFACE}
bind-interfaces
dhcp-range=${HW_DHCP_RANGE},1h
dhcp-option=option:router
enable-tftp
tftp-root=${TFTP_DIR}
dhcp-boot=Image,,${HW_HOST_IP}
EOF
}

# ── dnsmasq systemd user override ─────────────────────────────────────────────
# Arch (and many distros) ship dnsmasq.service with User=dnsmasq, which starts
# the process as a system user that cannot traverse mode-700 home directories.
# The dnsmasq `user=` config option is silently ignored when started as non-root.
# A drop-in that sets User=$(id -un) gives dnsmasq access to TFTP_DIR under ~/…
# while the AmbientCapabilities from the base unit (CAP_NET_BIND_SERVICE etc.)
# remain in effect, so dnsmasq can still bind ports 67/69.

dnsmasq_user_override() {
    cat <<EOF
# kernel-test hardware test network — generated by make hw-bootstrap
[Service]
User=$(id -un)
EOF
}

# ── systemd-networkd config ────────────────────────────────────────────────────
# Assigns HW_HOST_IP/24 to HW_IFACE as a static address.
# Prefix length is hardcoded to /24; HW_HOST_IP and HW_DHCP_RANGE must be in the same /24.
# ConfigureWithoutCarrier=yes: assign the IP even before a cable is plugged in so
# dnsmasq can bind to it immediately after hw-bootstrap runs.
# Only active on machines running systemd-networkd (not Hetzner).

networkd_conf() {
    cat <<EOF
# kernel-test hardware test network — generated by make hw-bootstrap
[Match]
Name=${HW_IFACE}

[Network]
ConfigureWithoutCarrier=yes
Address=${HW_HOST_IP}/24
EOF
}

# ── NetworkManager: mark HW_IFACE unmanaged ───────────────────────────────────
# When NetworkManager runs alongside systemd-networkd, NM reconfigures HW_IFACE
# on every carrier event (cable unplug/replug), stripping the static IP networkd
# assigned. Writing an unmanaged-devices entry makes NM ignore HW_IFACE entirely.

nm_unmanaged_conf() {
    cat <<EOF
# kernel-test hardware test network — generated by make hw-bootstrap
# Prevents NetworkManager from removing the static IP on HW_IFACE.
[keyfile]
unmanaged-devices=interface-name:${HW_IFACE}
EOF
}

# ── udev rule ──────────────────────────────────────────────────────────────────
# Creates stable /dev/vf2-relay symlink; sets group=dialout mode=0664.
# CH340 default VID=1a86 PID=7523; override with HW_RELAY_VID/HW_RELAY_PID in local.mk.
# Find your relay's IDs: udevadm info /dev/ttyUSB0 | grep ID_VENDOR_ID\|ID_MODEL_ID

udev_rule() {
    cat <<EOF
# VF2 USB relay board_reset — generated by make hw-bootstrap
# VID=${HW_RELAY_VID} PID=${HW_RELAY_PID} (CH340 default; override: HW_RELAY_VID/HW_RELAY_PID in local.mk)
# CH340-based relays enumerate as tty (SUBSYSTEM=="tty", /dev/ttyUSBx).
# HID-based relays (Ucreatefun etc.) enumerate as hidraw: change SUBSYSTEM=="tty" to SUBSYSTEM=="hidraw".
# Find your relay's IDs: udevadm info /dev/ttyUSB0 | grep ID_VENDOR_ID\|ID_MODEL_ID
SUBSYSTEM=="tty", ATTRS{idVendor}=="${HW_RELAY_VID}", ATTRS{idProduct}=="${HW_RELAY_PID}", GROUP="${SERIAL_GROUP}", MODE="0664", SYMLINK+="vf2-relay"
EOF
}

# ── Main ───────────────────────────────────────────────────────────────────────

if [[ $DRY_RUN -eq 1 ]]; then
    info "=== hw-bootstrap: hardware test network setup (DRY RUN) ==="
else
    info "=== hw-bootstrap: hardware test network setup ==="
fi
info "  HW_IFACE      = $HW_IFACE"
info "  HW_HOST_IP    = $HW_HOST_IP"
info "  HW_DHCP_RANGE = $HW_DHCP_RANGE"
info "  TFTP_DIR      = $TFTP_DIR"
info "  Relay VID:PID = ${HW_RELAY_VID}:${HW_RELAY_PID}"

# 1. Install dnsmasq
info "--- [1/6] dnsmasq package"
install_dnsmasq

# 2. dnsmasq config + systemd user override
info "--- [2/6] dnsmasq config → /etc/dnsmasq.d/vf2.conf"
ensure_dnsmasq_confd
write_file /etc/dnsmasq.d/vf2.conf "$(dnsmasq_conf)"
write_file /etc/systemd/system/dnsmasq.service.d/10-hw-bootstrap.conf "$(dnsmasq_user_override)"

# 3. systemd-networkd config
info "--- [3/6] systemd-networkd → /etc/systemd/network/50-vf2.network"
write_file /etc/systemd/network/50-vf2.network "$(networkd_conf)"

# 4. NetworkManager unmanaged rule (only when NM is running)
info "--- [4/6] NetworkManager unmanaged rule"
if systemctl is-active --quiet NetworkManager 2>/dev/null; then
    write_file /etc/NetworkManager/conf.d/99-vf2-unmanaged.conf "$(nm_unmanaged_conf)"
else
    info "NetworkManager not active — skipping"
fi

# 5. udev rule
info "--- [5/6] udev rule → /etc/udev/rules.d/99-vf2-relay.rules"
write_file /etc/udev/rules.d/99-vf2-relay.rules "$(udev_rule)"

# 6. TFTP dir
info "--- [6/6] TFTP directory: $TFTP_DIR"
if [[ $DRY_RUN -eq 1 ]]; then
    dry_info "would create: $TFTP_DIR"
else
    if [[ ! -d "$TFTP_DIR" ]]; then
        mkdir -p "$TFTP_DIR"
        info "created: $TFTP_DIR"
    else
        info "exists: $TFTP_DIR"
    fi
fi

# ── Activate (skip in dry-run) ─────────────────────────────────────────────────

if [[ $DRY_RUN -eq 0 ]]; then
    info "--- activating services"
    run_cmd $SUDO udevadm control --reload-rules
    run_cmd $SUDO udevadm trigger --subsystem-match=tty --subsystem-match=hidraw
    if systemctl is-active --quiet NetworkManager 2>/dev/null; then
        run_cmd $SUDO nmcli general reload
    fi
    run_cmd $SUDO systemctl enable --now systemd-networkd
    run_cmd $SUDO networkctl reload
    run_cmd $SUDO networkctl reconfigure "$HW_IFACE"
    run_cmd $SUDO systemctl daemon-reload
    run_cmd $SUDO systemctl restart dnsmasq
fi

if [[ $DRY_RUN -eq 1 ]]; then
    info "=== hw-bootstrap complete (DRY RUN) ==="
else
    info "=== hw-bootstrap complete ==="
fi

if [[ $DRY_RUN -eq 0 ]]; then
    printf '\nNext steps:\n'
    printf '  1. Plug in the USB relay — verify: ls -la /dev/vf2-relay\n'
    printf '  2. Connect Ethernet cable: laptop %s ↔ switch ↔ VF2 board\n' "$HW_IFACE"
    printf '  3. Run: make hw-deploy  (copies kernel + initramfs to %s/)\n' "$TFTP_DIR"
    printf '  4. Set U-Boot bootcmd once (see docs/hw-bootstrap-plan.md)\n'
    printf '  5. Run: make hw BOARD_TTY=/dev/ttyUSB0\n'
fi
